### ISSUE TITLE
Synthetic Texture Training and dataset format questions

### ISSUE THREAD

**Issue by Night1099** [tflsguoyu/svbrdf-diff-renderer#3]
Hello! I see youve been hard at work updating code!

Id like to train my stnyethic dataset is this possible what are the steps for that,

and how should the dataset be formated? 1280x256 images?

**Comment by tflsguoyu** [comment]
Are you going to train MaterialGAN with your synthetic data? 
We don't provide the code for that. You can check StyleGAN2 for the training.
The only difference is the data format, StyleGAN takes 256x256x3 images as input, but we take images with a resolution of 256x256x9. The 9 channels include 3 channels of ALBEDO (r, g, b), 2 channels of NORMAL (x, y), 1 channel of ROUGHNESS, and 3 channels of SPECULAR-ALBEDO (r, g, b).
